name: Build

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run: lein midje
    - name: Run clj-kondo linter
      uses: DeLaGuardo/clojure-lint-action@master
      with:
        clj-kondo-args: --lint src
        github_token: ${{ secrets.GITHUB_TOKEN }}
